name: CD

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  cd:
    uses: group-5-ingsis/workflows/.github/workflows/cd-containers.yml@main
    secrets:
      AZURE_DEV_KEY: ${{ secrets.AZURE_DEV_KEY }}
      AZURE_DEV_USER: ${{ secrets.AZURE_DEV_USER }}
      AZURE_DEV_HOST: ${{ secrets.AZURE_DEV_HOST }}